# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  services:
    - docker
  before_script:
    - docker build -t princearoraaws/docker-react -f Dockerfile.dev .
  script:
    - docker run -e CI=true princearoraaws/docker-react npm run test
  only:
    - master
