.cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/
      - vendor/
    policy: pull-push

default:
  cache:
    extends: .cache

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  before_script:
  - docker build -t princearoraaws/docker-react -f ./Dockerfile.dev .

  script:
  - docker run -e CI=true princearoraaws/docker-react npm run test-- --coverage

  only:
    - master
  tags:
    - docker