image: registry:5000/awscli-docker-stable:latest
# services:
#   - docker:stable-dind
    
# stages:
#   - build
#   - deploy

# Configuration
variables:
  EB_APP_ENV: "DockerReact-env" # ElasticBeanstalk Application Environment
  CI_DEBUG_TRACE: "true"

# build:
#   stage: build
#   before_script:
#   - docker build -t princearoraaws/docker-react -f ./Dockerfile.dev .

#   script:
#   - docker run -e CI=true princearoraaws/docker-react npm run test -- --coverage


#   only:
#     - master
#   tags:
#     - docker


deploy:
  stage: deploy
  before_script:
  # - apk add --update --no-cache python3 python3-dev curl gcc libffi-dev libc-dev openssl-dev build-base
  # - curl -O https://bootstrap.pypa.io/get-pip.py
  # - python3 get-pip.py
  # - pip --version
  # - pip install awsebcli --upgrade
#  - eb --version
  # - pip install awscli --upgrade
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION

  script:
#  - docker build -t princearoraaws/docker-react .
  - yes n | eb init
  - echo "eb init done"
  - eb status $EB_APP_ENV
  - eb deploy $EB_APP_ENV 
  - eb status $EB_APP_ENV 
  #- aws s3 cp build/libs/mySampleApp.war s3://elasticbeanstalk-eu-central-1-11111222222233/mySampleApp-$CI_PIPELINE_ID.war


  only:
    - master
  tags:
    - docker
