image: docker:latest
build_job:
  stage: build

  before_script:
    - ls
    - echo "starting job..."
    - docker build -t princearoraaws/docker-react -f Dockerfile.dev .
    - echo job finished
  script:
    - docker run -e CI=true princearoraaws/docker-react npm run test
  only:
    - master
  tags:
    - docker
