image: docker:latest
build_job:
  stage: build
  services:
    - docker
  before_script:
    - docker build -t princearoraaws/docker-react -f Dockerfile.dev .
  script:
    - docker run -e CI=true princearoraaws/docker-react npm run test
  only:
    - master
  tags:
    - docker
