image: docker:stable

services:
  - docker:stable-dind

stages:
  - build
  - deploy

# Configuration
variables:
  EB_APP_ENV: "DockerReact-env" # ElasticBeanstalk Application Environment


build:
  stage: build
  before_script:
  - docker build -t princearoraaws/docker-react -f ./Dockerfile.dev .

  script:
  - docker run -e CI=true princearoraaws/docker-react npm run test -- --coverage


  only:
    - master
  tags:
    - docker


deploy:
  stage: deploy
  #image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  image:  python:slim
  script:
  - pip install awsebcli --upgrade --user
  - pip install awscli --upgrade --user
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - eb status $EB_APP_ENV
  - eb deploy $EB_APP_ENV  
  #- aws s3 cp build/libs/mySampleApp.war s3://elasticbeanstalk-eu-central-1-11111222222233/mySampleApp-$CI_PIPELINE_ID.war


  only:
    - master
  tags:
    - docker
