version: '3.8'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 5000:3000
    volumes: 
      - /app/node_modules
      - .:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: npm run test

