branch-defaults:
  master:
    environment: Dockerreact-env
environment-defaults:
  Dockerreact-env:
    branch: null
    repository: null
global:
  application_name: docker-react
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: ap-south-1
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application